[package]
# cf - Cached & Fast, or: Cache-Friendly
name = "cfc"
version = "0.1.0"
edition = "2021"

categories = ["algorithms", "caching", "data-structures", "no-std", "text-processing"]

authors = ["Peter Kehl <peter.kehl@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/peter-kehl/cfc"

# [lib]

[dependencies]
