[package]
name = "camigo"
version = "0.0.1"
edition = "2018"

description = "Cache-friendly comparison, binary & sequential search."
categories = ["algorithms", "caching", "data-structures", "no-std", "text-processing"]

authors = ["Peter Kehl <peter.kehl@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/peter-kehl/camigo"

# TODO MSRV

[features]
# Keep features here sorted alphabetically
alloc = []

# TODO See if this comment shows up at docs.rs.
std = ["alloc"]

deref_pure = ["unsafe", "nightly"]
hint_assert_unchecked = ["unsafe"]
nightly = []

transmute = ["unsafe"]
unsafe = []
wrappers = []

# TODO:
#default = ["std", "wrappers", "transmute", "deref_pure"]
default = []

[dependencies]
camigo-helpers = { path = "../camigo-helpers", version = "0.0.1" }

[dev-dependencies]
# @TODO real_blackbox is on NIGHTLY only - do this depending on rustc channel?
# criterion = { version = "0.5.1", features=['real_blackbox'] }
criterion = { version = "0.5.1" }

fastrand = { version = "2.0.2"}

[[bench]]
name = "vec_strings"
harness = false

[[bench]]
name = "vec_u8"
harness = false

[lints.rust]
#warnings = "allow"
