[package]
name = "camigo"
version = "0.0.1"
edition = "2021"

description = "Cache-friendly comparison, binary & sequential search."
categories = ["algorithms", "caching", "data-structures", "no-std", "text-processing"]

authors = ["Peter Kehl <peter.kehl@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/peter-kehl/camigo"

[features]
# Keep features here sorted alphabetically
alloc = []
std = ["alloc"]
deref_pure_trait = ["unsafe"]
hint_assert_unchecked = ["unsafe"]
nightly = []
real_blackbox = [] #TODO
unsafe = []

#default = ["hint_assert_unchecked"]
default = []
#default = ["alloc"]

[dependencies]

[dev-dependencies]
# @TODO real_blackbox is on NIGHTLY only - do this depending on rustc channel?
# criterion = { version = "0.5.1", features=['real_blackbox'] }
criterion = { version = "0.5.1" }

[[bench]]
name = "with_criterion"
harness = false